apiVersion: v2
name: worldofgames-chart
description: A Helm chart for deploying the WorldOfGames application
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: 9.9.1
    repository: "https://charts.bitnami.com/bitnami"
